#PROGRAM STATEMENT
>Write a program to implement Naive Bayes Classification on given data set to design a model that can predict whether player will play on a given day on the basis of the provided features.

#CODE

In [ ]:
# Assigning features and label variables
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny',
         'Sunny', 'Rainy','Sunny','Overcast','Overcast','Rainy']

temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild',
      'Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes',
      'No']

humidity=['High','High','High','High','Normal','Normal','Normal','High','Normal',
          'Normal','Normal','High','Normal','High']

wind=['Normal','Strong','Normal','Normal','Normal','Strong','Strong','Normal',
      'Normal','Normal','Strong','Strong','Normal','Strong']

import pandas as pd
df = pd.DataFrame(list(zip(weather, temp, humidity, wind, play)),
               columns =['Weather', 'Temp', 'Humidity', 'Wind', 'Play'])

#Dataset
df

Weather  Temp Humidity    Wind Play
0      Sunny   Hot     High  Normal   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High  Normal  Yes
3      Rainy  Mild     High  Normal  Yes
4      Rainy  Cool   Normal  Normal  Yes
5      Rainy  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High  Normal   No
8      Sunny  Cool   Normal  Normal  Yes
9      Rainy  Mild   Normal  Normal  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal  Normal  Yes
13     Rainy  Mild     High  Strong   No

In [11]:
# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
weather_encoded=le.fit_transform(weather)
temp_encoded=le.fit_transform(temp)
humidity_encoded = le.fit_transform(humidity)
wind_encoded = le.fit_transform(wind)
target=le.fit_transform(play)

In [12]:
# 0:Overcast 1:Rainy 2:Sunny
print(weather_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [13]:
# 0:Cool 1:Hot 2:Mild
print(temp_encoded)

[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [14]:
# 0:High 1:Normal
print(humidity_encoded)

[0 0 0 0 1 1 1 0 1 1 1 0 1 0]


In [15]:
# 0:Strong 1:Normal
print(wind_encoded)

[0 1 0 0 0 1 1 0 0 0 1 1 0 1]


In [16]:
# 0:NO 1:YES
print(target)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [17]:
import numpy as np
zipped=zip(weather_encoded,temp_encoded,humidity_encoded,wind_encoded)
features = np.array(list(zipped)).tolist()

In [18]:
print(features)

[[2, 1, 0, 0], [2, 1, 0, 1], [0, 1, 0, 0], [1, 2, 0, 0], [1, 0, 1, 0], [1, 0, 1, 1], [0, 0, 1, 1], [2, 2, 0, 0], [2, 0, 1, 0], [1, 2, 1, 0], [2, 2, 1, 1], [0, 2, 0, 1], [0, 1, 1, 0], [1, 2, 0, 1]]


In [52]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.10)

#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import CategoricalNB

#Create a Gaussian Classifier
model = CategoricalNB()

# Train the model using the training sets
model.fit(X_train, y_train)

# Test the model using test set
y_pred = model.predict(X_test) 

from sklearn.metrics import classification_report, confusion_matrix  
# Confusion Matrix
print(confusion_matrix(y_test, y_pred))

[[1 0]
 [0 1]]


In [53]:
# Classification Report
print(classification_report(y_test, y_pred)) 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2



In [54]:
#Predict Output
predicted= model.predict([[2, 0, 0, 0]]) # (Weather, Tempreature, Humidity, Wind) = (2:Overcast, 0:Cool, 0:High, 0:Strong) 
print("Predicted Value:", predicted)

Predicted Value: [0]


In [55]:
%%capture
!wget -nc https://raw.githubusercontent.com/brpy/colab-pdf/master/colab_pdf.py
from colab_pdf import colab_pdf
colab_pdf('Naive Bayes Classification.ipynb')