In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
dataset = pd.read_csv("/content/drive/MyDrive/Datasets/covid19_fake.csv")

In [4]:
# Assigning features and label variables
Fever = dataset['Fever'].tolist()
Cough = dataset['Cough'].tolist()
BreathIssues = dataset['Breathing issues'].tolist()
Infected = dataset['Infected'].tolist()

In [5]:
print(Fever)
print(Cough)
print(BreathIssues)
print(Infected)

['NO', 'YES', 'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'NO', 'YES', 'NO', 'NO', 'NO', 'YES']
['NO', 'YES', 'YES', 'NO', 'YES', 'YES', 'NO', 'NO', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES']
['NO', 'YES', 'NO', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'NO', 'NO', 'YES', 'YES', 'NO']
['NO', 'YES', 'NO', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'YES', 'NO', 'YES', 'NO', 'NO']


In [8]:
# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
fever_encoded = le.fit_transform(Fever)
cough_encoded = le.fit_transform(Cough)
breathIssues_encoded = le.fit_transform(BreathIssues)
target = le.fit_transform(Infected)

print(fever_encoded)
print(cough_encoded)
print(breathIssues_encoded)
print(target)

import numpy as np
zipped=zip(fever_encoded,cough_encoded,breathIssues_encoded)
features = np.array(list(zipped)).tolist()
print(features)

#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import CategoricalNB

#Create a Gaussian Classifier
model = CategoricalNB()

# Train the model using the training sets
model.fit(features,target)

#Predict Output
predicted= model.predict([[0, 1, 0]]) # 0:Overcast, 2:Mild 
print("Predicted Value:", predicted)


[0 1 1 1 1 0 1 1 0 1 0 0 0 1]
[0 1 1 0 1 1 0 0 1 1 1 1 1 1]
[0 1 0 1 1 0 1 1 1 0 0 1 1 0]
[0 1 0 1 1 0 1 1 1 1 0 1 0 0]
[[0, 0, 0], [1, 1, 1], [1, 1, 0], [1, 0, 1], [1, 1, 1], [0, 1, 0], [1, 0, 1], [1, 0, 1], [0, 1, 1], [1, 1, 0], [0, 1, 0], [0, 1, 1], [0, 1, 1], [1, 1, 0]]
Predicted Value: [0]
